# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages

services:
  - MySQL
  - postgresql
addons:
  postgresql: "9.4"

# Seems to be necessary with devtools 1.10.0, check again when the next version is on CRAN
r_github_packages:
  - rstats-db/DBI
  - hadley/testthat

before_install:
  - mysql -e "CREATE DATABASE IF NOT EXISTS test;" -uroot
  - mysql -e "GRANT ALL PRIVILEGES ON test.* TO 'travis'@'localhost'; FLUSH PRIVILEGES;" -uroot

notifications:
  email:
    on_success: change
    on_failure: change
