# Info:
# https://docs.travis-ci.com/user/languages/r/
# https://docs.travis-ci.com/user/database-setup/#MySQL

language: r
cache: packages
latex: false
sudo: false
dist: trusty

services:
  - MySQL
  - postgresql
addons:
  postgresql: "9.4"
  apt:
    packages:
      - libmysqlclient-dev
      - libpq-dev

#r_check_revdep: true

r_packages:
  - roxygen2

# Seems to be necessary with devtools 1.10.0, check again when the next version is on CRAN
r_github_packages:
  - rstats-db/DBI
  - hadley/testthat

before_install:
  - mysql -e "CREATE DATABASE IF NOT EXISTS test;" -uroot
  - mysql -e "GRANT ALL PRIVILEGES ON test.* TO 'travis'@'localhost'; FLUSH PRIVILEGES;" -uroot

before_script:
  - travis_retry mysql -e "CREATE DATABASE IF NOT EXISTS test; ALTER DATABASE test CHARACTER SET 'utf8'; FLUSH PRIVILEGES;" -uroot
  - travis_retry mysql -e "CREATE USER '"${USER}"'@'localhost'; FLUSH PRIVILEGES;" -uroot || true
  - travis_retry mysql -e "GRANT ALL PRIVILEGES ON test.* TO '"${USER}"'@'localhost'; FLUSH PRIVILEGES;" -uroot
  - make --keep-going --directory=revdep-dev

notifications:
  email:
    on_success: change
    on_failure: change
