language: c
# To build on OSX, switch the previous line to
# language: objective-c
sudo: required
env:
  global:
    - NOT_CRAN=true
    - LINTR_COMMENT_BOT=0

script:
  - ./travis-tool.sh run_tests
  - make -C revdep-dev

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap

install:
  - ./travis-tool.sh install_github krlmlr/DBI
  - ./travis-tool.sh dump_sysinfo

after_failure:
  - cat tikzDevice.Rcheck/00install.out || true
  - cat tikzDevice.Rcheck/00check.log || true
